#!/usr/bin/env bash
set -euo pipefail

BLOCKLIST_URL="https://raw.githubusercontent.com/yashashav-dk/fmhy-blocklist/main/blocklist.txt"
ETAG_CACHE="/tmp/.fmhy-blocklist-etag"
HOSTS_FILE="/etc/hosts"
MARKER_START="# ===== FMHY BLOCKLIST START ====="
MARKER_END="# ===== FMHY BLOCKLIST END ====="
LOG_TAG="fmhy-blocklist"

log() { logger -t "$LOG_TAG" "$*" 2>/dev/null; echo "[apply-hosts] $*"; }

CURL_ARGS=(-fsSL --max-time 30)
if [[ -f "$ETAG_CACHE" ]]; then
  CACHED_ETAG="$(cat "$ETAG_CACHE")"
  CURL_ARGS+=(-H "If-None-Match: $CACHED_ETAG")
fi

HTTP_CODE=$(curl "${CURL_ARGS[@]}" -o /tmp/.fmhy-blocklist-raw -w "%{http_code}" "$BLOCKLIST_URL" 2>/dev/null || echo "000")

if [[ "$HTTP_CODE" == "304" ]]; then
  log "Blocklist unchanged (304), skipping"
  exit 0
fi

if [[ "$HTTP_CODE" != "200" ]]; then
  log "ERROR: Failed to fetch blocklist (HTTP $HTTP_CODE)"
  exit 1
fi

curl -fsSL -I "$BLOCKLIST_URL" 2>/dev/null | grep -i "^etag:" | awk '{print $2}' | tr -d '\r' > "$ETAG_CACHE"

BLOCK_ENTRIES=$(grep '^||' /tmp/.fmhy-blocklist-raw | sed 's/^||//; s/\^$//' | sort -u | while read -r domain; do
  echo "0.0.0.0 $domain"
done)

DOMAIN_COUNT=$(echo "$BLOCK_ENTRIES" | wc -l | tr -d ' ')

if [[ "$DOMAIN_COUNT" -lt 100 ]]; then
  log "ERROR: Only $DOMAIN_COUNT domains extracted — something is wrong. Aborting."
  exit 1
fi

cp "$HOSTS_FILE" "${HOSTS_FILE}.fmhy-backup.$(date +%Y%m%d%H%M%S)"
ls -t "${HOSTS_FILE}".fmhy-backup.* 2>/dev/null | tail -n +6 | xargs rm -f 2>/dev/null || true

if grep -q "$MARKER_START" "$HOSTS_FILE"; then
  sed -i.tmp "/$MARKER_START/,/$MARKER_END/d" "$HOSTS_FILE"
  rm -f "${HOSTS_FILE}.tmp"
fi

{
  echo ""
  echo "$MARKER_START"
  echo "# Auto-generated by fmhy-blocklist — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# $DOMAIN_COUNT domains | https://github.com/yashashav-dk/fmhy-blocklist"
  echo "$BLOCK_ENTRIES"
  echo "$MARKER_END"
} >> "$HOSTS_FILE"

OS="$(uname -s)"
if [[ "$OS" == "Darwin" ]]; then
  dscacheutil -flushcache
  killall -HUP mDNSResponder 2>/dev/null || true
  log "DNS cache flushed (macOS)"
elif [[ "$OS" == "Linux" ]]; then
  systemctl restart systemd-resolved 2>/dev/null || true
  log "DNS cache flushed (Linux)"
fi

log "Applied $DOMAIN_COUNT domains to $HOSTS_FILE"
rm -f /tmp/.fmhy-blocklist-raw
